server.port: 8081

spring:

  application:
    name: hotels-ms

  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/hotels?useSSL=false
    username: root