server.port: 8082

spring:

  application:
    name: flights-ms

  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/flights?useSSL=false
    username: root